---
title: "Nishan Ghimire: Master's Research Project (MRP) Results"
output:
  pdf_document: default
date: "January 16, 2026"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(AER)
library(kableExtra)
library(rio)  
library(xtable)
library(foreign)
library(modelsummary)
library(MASS)
library(jtools)
library(readxl)
library(knitr)
library(stargazer)
library(readxl)
library(rineq)
library(dplyr) 
library(kableExtra)
library(reldist)

```

<!-- Please change this address to run the WHOLE program successfully -->

```{r, results='asis', echo=FALSE}


setwd("/Users/nishanghimire/Library/CloudStorage/OneDrive-Personal/MRP OneDrive/Github version/") ## Please change this address to run the WHOLE program successfully.

```



<!--Throughout the entire program , line "list(sqrt(diag(sandwich::vcovHC(model#, type = "HC3"))))" is for heteroskedasticity robust standard errors

<!--This block below computes regression estimates for US (Total Federal Taxes) from 1979-2021 -->


```{r, results='asis', echo=FALSE}



data1 <- read_excel("US Regression 1979-2021.xlsx", sheet = "Table for Regression") 

model1 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = data1)

robust_se <- list(sqrt(diag(sandwich::vcovHC(model1, type = "HC3")))) 

stargazer(model1,
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "US Regression Results for 1979-2021",
          se = robust_se)

```

<!--This block computes regression estimates for US (Total Federal Taxes) for 1979-1999 and 2000-2021-->


```{r, results='asis', echo=FALSE}


subset_data1 <- data1[1:105, ]
subset_data2 <- data1[106:201, ]


model2 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data1 )
model3 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data2 )


robust_se2 <- sqrt(diag(sandwich::vcovHC(model2, type = "HC3")))
robust_se3 <- sqrt(diag(sandwich::vcovHC(model3, type = "HC3")))

robust_se_list <- list(robust_se2, robust_se3)

stargazer(model2, model3,
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "US Regression Results 1979-1999 and 2000-2021",
          se = robust_se_list)


```


<!--This block below computes regression estimates for Canada from 1992-2022 using federal income taxes -->


```{r, results='asis', echo=FALSE}


data2 <- read_excel("1992-2022 Canada Regression.xlsx", sheet = "Table for Regression") 

model4 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = data2)

robust_se1 <- list(sqrt(diag(sandwich::vcovHC(model4, type = "HC3"))))

stargazer(model4, 
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "Canada Regression Results 1992-2022 (Using Federal Income Taxes)",
          se = robust_se1)

```

<!--This block computes regression estimates for Canada (Federal Income Taxes) from 1992-2006 and 2007-2022 -->


```{r, results='asis', echo=FALSE}


subset_data3 <- data2[1:75, ]
subset_data4 <- data2[76:155, ]


model5 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data3)
model6 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data4)

robust_se5 <- sqrt(diag(sandwich::vcovHC(model5, type = "HC3")))

robust_se6 <- sqrt(diag(sandwich::vcovHC(model6, type = "HC3")))

robust_se_list56 <- list(robust_se5, robust_se6)

stargazer(model5, model6,
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "Canada Regression Results 1992-2006 and 2007-2022 (Using Federal Income Taxes)",
          se = robust_se_list56)

```

<!--This block below computes regression estimates for Canada from 1992-2022 using federal and provincial income taxes -->


```{r, results='asis', echo=FALSE}

data3 <- read_excel("Fed and Prov 1992-2022 Canada.xlsx", sheet = "Table for Regression") 

model7 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = data3)

robust_se7 <- list(sqrt(diag(sandwich::vcovHC(model7, type = "HC3"))))

stargazer(model7, 
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "Canada Regression Results 1992-2022 (Using Federal and Provincial Income Taxes)",
          se = robust_se7)
```

<!--This block computes regression estimates for Canada (federal & provincial income Taxes) from 1992-2006 and 2007-2022 -->

```{r, results='asis', echo=FALSE}


subset_data5 <- data3[1:75, ]
subset_data6 <- data3[76:155, ]


model8 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data5)
model9 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data6)


robust_se8 <- sqrt(diag(sandwich::vcovHC(model8, type = "HC3")))

robust_se9 <- sqrt(diag(sandwich::vcovHC(model9, type = "HC3")))

robust_se_list89 <- list(robust_se8, robust_se9)

stargazer(model8, model9,
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "Canada Regression Results 1992-2006 and 2007-2022 (Using Federal and Provincial Income Taxes)",
          se = robust_se_list89)

```
<!--Values of phi & eta   -->



```{r, results='asis', echo=FALSE}

## Values of phi & eta  

coef_table <- data.frame(
  Model = c(
    "US: Total Federal Taxes (1979-2021)",
    "US: Total Federal Taxes (1979-1999)",
    "US: Total Federal Taxes (2000-2021)",
    "Canada: Federal Income Taxes (1992-2022)",
    "Canada: Federal Income Taxes (1992-2006)",
    "Canada: Federal Income Taxes (2007-2022)",
    "Canada: Federal and Provincial Income Taxes (1992-2022)",
    "Canada: Federal and Provincial Income Taxes (1992-2006)",
    "Canada: Federal and Provincial Income Taxes (2007-2022)"
    
  ),
  eta = round(c(exp(coef(model1)[1]), exp(coef(model2)[1]), exp(coef(model3)[1]),
                exp(coef(model4)[1]), exp(coef(model5)[1]),
                exp(coef(model6)[1]), exp(coef(model7)[1]),
                exp(coef(model8)[1]), exp(coef(model9)[1])), 3),
  phi = round(c(coef(model1)[2], coef(model2)[2], coef(model3)[2],
                coef(model4)[2], coef(model5)[2],
                coef(model6)[2], coef(model7)[2],
                coef(model8)[2], coef(model9)[2]), 3)
)

colnames(coef_table) <- c("Model", "$\\eta$", "$\\phi$")

kable(coef_table, format = "latex", escape = FALSE,
      caption = "Estimated Parameters: $\\eta$ and $\\phi$")

```


<!-- OECD Data Results for Canada (2000-2020), (2000-2010), (2010-2020)  -->

```{r, results='asis', echo=FALSE}

data4 <- read_excel("Canada Regression OECD results.xlsx", sheet = "Table for Regression") 

model10 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = data4)

robust_se10 <- sqrt(diag(sandwich::vcovHC(model10, type = "HC3")))

subset_data7 <- data4[1:33, ]
subset_data8 <- data4[34:63, ]


model11 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data7)
model12 <- lm(`LHS of the equation` ~ `LN of Primary Income Shares`, data = subset_data8)


robust_se11 <- sqrt(diag(sandwich::vcovHC(model11, type = "HC3")))

robust_se12 <- sqrt(diag(sandwich::vcovHC(model12, type = "HC3")))

robust_se_listOECD <- list(robust_se10, robust_se11, robust_se12)

stargazer(model10, model11, model12,
          type = "latex", 
          dep.var.labels = "LHS of the equation",
          covariate.labels = c("LN of Primary Income Shares"),
          title = "Canada Results OECD, 2000-2020, 2000-2010, 2010-2020",
          se = robust_se_listOECD)

```

<!-- Kakwani and RS index for US 1979-2021  -->


```{r, results='asis', echo=FALSE}


data_US_for_Kakwani <- read_excel("Sample for Kakwani Index.xlsx", sheet = "US") 

#This computes before tax GINI

gini_results <- data_US_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    gini = gini(income, weights = population_share)
  )

#This computes tax concentration index

tax_concentration_results <- data_US_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    tax_conc_index = ci(
      ineqvar = income,
      outcome = taxes,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data <- merge(gini_results, tax_concentration_results, by = "year")

#This computes Kakwani index by subtracting tax_concentration index with before tax gini

kakwani <- merged_data %>%
  mutate(Kakwani_index = tax_conc_index - gini)

data_US_for_RSIndex <- read_excel("Sample for RS Index.xlsx", sheet = "US") 

#There are two ways to compute RS index which will lead the same result: either subtract Gini pre tax and after tax or simply use pre tax income in the tax concentration formula and subtract this with after tax Gini. 

#Method 1:

gini_results_usa<- data_US_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini_pre = gini(pretaxincome, weights = population_share),
    gini_after = gini(aftertaxincome, weights = population_share),
    RSIndex =  gini_pre - gini_after 
  )


#Method 2:

#This computes after tax GINI

gini_results1 <- data_US_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini = gini(aftertaxincome, weights = population_share)
  )

#This computes before tax income concentration index

pretaxincome_index<- data_US_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    pre_tax_income_index = ci(
      ineqvar = aftertaxincome,
      outcome = pretaxincome,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data1 <- merge(gini_results1, pretaxincome_index, by = "year")

RSindex <- merged_data1 %>%
  mutate(RS_Index = pre_tax_income_index - gini)

final_table <- merge(
  kakwani[, c("year", "Kakwani_index")],
  RSindex[, c("year", "RS_Index")],
  by = "year"
)

kable(final_table, caption = "Kakwani and RS Index by Year for US 1979-2021")

```


<!-- Kakwani and RS index for Canada 1992-2022 (Federal Income Tax)  -->

```{r, results='asis', echo=FALSE}


data_Canada_for_Kakwani <- read_excel("Sample for Kakwani Index.xlsx", sheet = "Canada (Federal)") 

#This computes before tax GINI

gini_results <- data_Canada_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    gini = gini(income, weights = population_share)
  )

#This computes tax concentration index

tax_concentration_results <- data_Canada_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    tax_conc_index = ci(
      ineqvar = income,
      outcome = taxes,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data <- merge(gini_results, tax_concentration_results, by = "year")

#This computes Kakwani index by subtracting tax_concentration index with before tax gini

kakwani <- merged_data %>%
  mutate(Kakwani_index = tax_conc_index - gini)

data_Canada_for_RSIndex <- read_excel("Sample for RS Index.xlsx", sheet = "Canada (Federal)") 

#There are two ways to compute RS index which will lead the same result: either subtract Gini pre tax and after tax or simply use pre tax income in the tax concentration formula and subtract this with after tax Gini. 

#Method 1:

gini_results_Canada<- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini_pre = gini(pretaxincome, weights = population_share),
    gini_after = gini(aftertaxincome, weights = population_share),
    RSIndex =  gini_pre - gini_after 
  )


#Method 2:

#This computes after tax GINI

gini_results1 <- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini = gini(aftertaxincome, weights = population_share)
  )

#This computes before tax income concentration index

pretaxincome_index<- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    pre_tax_income_index = ci(
      ineqvar = aftertaxincome,
      outcome = pretaxincome,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data1 <- merge(gini_results1, pretaxincome_index, by = "year")

RSindex <- merged_data1 %>%
  mutate(RS_Index = pre_tax_income_index - gini)

final_table <- merge(
  kakwani[, c("year", "Kakwani_index")],
  RSindex[, c("year", "RS_Index")],
  by = "year"
)

kable(final_table, caption = "Kakwani and RS Index by Year for Canada (Using Federal Income Tax) 1992-2022")
```



<!-- Kakwani and RS index for Canada 1992-2022 (Federal and Provincial Income Tax)  -->

```{r, results='asis', echo=FALSE}

data_Canada_for_Kakwani <- read_excel("Sample for Kakwani Index.xlsx", sheet = "Canada (Federal and Prov)") 

#This computes before tax GINI

gini_results <- data_Canada_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    gini = gini(income, weights = population_share)
  )

#This computes tax concentration index

tax_concentration_results <- data_Canada_for_Kakwani  %>%
  group_by(year) %>%
  summarise(
    tax_conc_index = ci(
      ineqvar = income,
      outcome = taxes,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data <- merge(gini_results, tax_concentration_results, by = "year")

#This computes Kakwani index by subtracting tax_concentration index with before tax gini

kakwani <- merged_data %>%
  mutate(Kakwani_index = tax_conc_index - gini)

data_Canada_for_RSIndex <- read_excel("Sample for RS Index.xlsx", sheet = "Canada (Federal and Prov)") 

#There are two ways to compute RS index which will lead the same result: either subtract Gini pre tax and after tax or simply use pre tax income in the tax concentration formula and subtract this with after tax Gini

#Method 1:

gini_results_Canada<- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini_pre = gini(pretaxincome, weights = population_share),
    gini_after = gini(aftertaxincome, weights = population_share),
    RSIndex =  gini_pre - gini_after 
  )


#Method 2:

#This computes after tax GINI

gini_results1 <- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    gini = gini(aftertaxincome, weights = population_share)
  )

#This computes before tax income concentration index

pretaxincome_index<- data_Canada_for_RSIndex %>%
  group_by(year) %>%
  summarise(
    pre_tax_income_index = ci(
      ineqvar = aftertaxincome,
      outcome = pretaxincome,
      weights = population_share,
      type = "CI"
    )[["concentration_index"]]
  )

merged_data1 <- merge(gini_results1, pretaxincome_index, by = "year")

RSindex <- merged_data1 %>%
  mutate(RS_Index = pre_tax_income_index - gini)

final_table <- merge(
  kakwani[, c("year", "Kakwani_index")],
  RSindex[, c("year", "RS_Index")],
  by = "year"
)

kable(final_table, caption = "Kakwani and RS Index by Year for Canada (Using Federal and Provincial Income Tax) 1992-2022")
```



